apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv
  labels:
    pv: host-path
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /usr/k8s/data
